### PR TITLE
Updates to Ruby and Swift

### PR DESCRIPTION
**Pull request by hsavit1**
added a few things

### CODE REVIEW

**Comment by tayllan** [comment]
Damn, a rather complicated PR you have there.
I really appreciate man, but I'd like you to submit one change per PR (like it's suggested in the [contributing.md](https://github.com/tayllan/awesome-algorithms/blob/master/CONTRIBUTING.md)) because it's somewhat difficult to see exactly what you changed here.
Besides that, I don't think the [red-black tree repo](https://github.com/prachigauriar/RedBlack) belongs here, being a too specific algorithms and all. The [coding challenges](https://github.com/donnemartin/interactive-coding-challenges) is already included under the [tools section](https://github.com/tayllan/awesome-algorithms#tools). And you added some extra/undesired spaces on some places.
Thanks anyway.

**Comment by hsavit1** [comment]
Hey,

Sorry I didn't even realize that I added so many additions to the pr! I
really just meant to add the Ruby and swift additions. I eventually just
started committing more for my own personal purposes and I didn't realize
that this would update here too!
don't do many pr's

Really, the only thing I wanted to contribute here are the Ruby and swift
additions. Everything else was just meant to be on my own fork. I realize
that they're out of scope - Sorry about that !

On Saturday, August 8, 2015, Tayllan Búrigo <notifications@github.com>
wrote:

> Damn, a rather complicated PR you have there.
> I really appreciate man, but I'd like you to submit one change per PR
> (like it's suggested in the contributing.md
> <https://github.com/tayllan/awesome-algorithms/blob/master/CONTRIBUTING.md>)
> because it's somewhat difficult to see exactly what you changed here.
> Besides that, I don't think the red-black tree repo
> <https://github.com/prachigauriar/RedBlack> belongs here, being a too
> specific algorithms and all. The coding challenges
> <https://github.com/donnemartin/interactive-coding-challenges> is already
> included under the tools section
> <https://github.com/tayllan/awesome-algorithms#tools>. And you added some
> extra/undesired spaces on some places.
> Thanks anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tayllan/awesome-algorithms/pull/19#issuecomment-129041611>
> .
>


-- 
Sent from Gmail Mobile

**Comment by tayllan** [comment]
No problem, I ran on the same problem once on GitHub too :smile: , and while I don't really know how you could fix it, I'm looking forward for your contribution.

**Comment by hsavit1** [comment]
I'll make a separate pr with just those additions

On Saturday, August 8, 2015, Tayllan Búrigo <notifications@github.com>
wrote:

> No problem, I ran on the same problem once on GitHub too [image: :smile:]
> , and while I don't really know how you could fix it, I'm looking forward
> for your contribution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tayllan/awesome-algorithms/pull/19#issuecomment-129042112>
> .
>


-- 
Sent from Gmail Mobile

**Comment by hsavit1** [comment]
I think this is an important repo and I wouldn't want to ruin it with my
own personal additions

On Saturday, August 8, 2015, Henry Savit <henrysavit@gmail.com> wrote:

> I'll make a separate pr with just those additions
>
> On Saturday, August 8, 2015, Tayllan Búrigo <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> No problem, I ran on the same problem once on GitHub too [image: :smile:]
>> , and while I don't really know how you could fix it, I'm looking forward
>> for your contribution.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tayllan/awesome-algorithms/pull/19#issuecomment-129042112>
>> .
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Pull request closed without merging**
