### PR TITLE
Add Codility to Online Judges

### PR DESCRIPTION
**Pull request by pbitkowski**

### CODE REVIEW

**Comment by tayllan** [comment]
Hey @pbitkowski , thanks for the contribution. But this doesn't seem a good addition to the repo, since it's not focused primarily on algorithms, and it's not even accessible without a demo.

**Comment by pbitkowski** [comment]
Hi @tayllan 

Check those links: 
- challenges: https://app.codility.com/programmers/challenges/
- algorithmic lessons: https://app.codility.com/programmers/lessons/1-iterations/

Maybe those will be a better fit? 

Thanks for your time!

**Comment by tayllan** [comment]
Hey @pbitkowski , yeah, now I see it.

I think it makes sense to add [challenges](https://app.codility.com/programmers/challenges/) to the **Online Judges** section, and the [lessons](https://app.codility.com/programmers/lessons/1-iterations/) are easily accessible from there too, so there's no need for a separate link here.

What do you think? Can you update the PR if you agree with it?

Cheers.

**Comment by pbitkowski** [comment]
I agree. The PR has been changed :)

**Pull request merged**
