### PR TITLE
add youtube as a new category with some resources

### PR DESCRIPTION
**Pull request by alaminrifat**
added a new category named youtube to excellent complete tutorials available on youtube as a long-duration tutorial and complete playlist.

### CODE REVIEW

**Comment by mostafatouny** [comment]
Farewell. Add a new section of YouTube Playlists in between _Websites_ and _Online Courses_. Try to follow the same format and do not forget the table of contents

**Comment by alaminrifat** [comment]
ok I am doing

**Comment by alaminrifat** [comment]
I have made a new commit based on your requirement. Please check @mostafatouny

**Comment by mostafatouny** [comment]
Thank you for your time, @alaminrifat.

**Pull request merged**
