### PR TITLE
Hope coderbyte is valid here

### PR DESCRIPTION
**Pull request by kotAPI**
update coderbyte

### CODE REVIEW

**Comment by tayllan** [comment]
Hum, while the site in itself seems nice and useful, every content I tried to access is available to premium users only, what kind of goes against the list don't you think?

**Comment by kotAPI** [comment]
It's been a while since I've used it, it was well and good and helped me quite a bit to prepare for job interviews. I think the algorithm track is free for everyone, stuff other than the free ones are pretty much lacking and useless anyway. 

https://coderbyte.com/challenges/

These are pretty much free to access, Most of the hard challenges are pretty challenging and serve as good brain teasers. I guess that's good enough, right?

**Comment by tayllan** [comment]
Yes, I failed to see the open content. Unfortunately, I'm having problems merging your PR now, because it's conflicting with another PR I accepted Monday. Could you perhaps [rebase](http://www.git-scm.com/book/en/v2/Git-Branching-Rebasing) it so that I can accept it? Thanks.

**Comment by kotAPI** [comment]
Sure. Will do it soon.

**Comment by tayllan** [comment]
Closed in #36.

**Pull request closed without merging**
