### PR TITLE
Add links to iOS and Android apps for algorithm and data structure visualization

### PR DESCRIPTION
**Pull request by IevgenOvsii**
Added links to my mobile apps (iOS and Android).

The apps provide interactive visualizations for a variety of algorithms and data structures, including Kruskal’s algorithm, Union-Find, Red-Black Tree, and more.

I believe this addition will offer value to users seeking hands-on, visual learning tools. Please review and consider merging. Thank you!

P.S. If a review of the apps is needed, I'd be happy to provide promo codes for access.

### CODE REVIEW

**Comment by mostafatouny** [comment]
Thank you for reaching out. How are those apps distinguished from already listed resources? @IevgenOvsii

**Comment by IevgenOvsii** [comment]
@mostafatouny Thank you for the question! They are mobile-friendly, work offline, and provide well-prepared information from basic data structures to more complex ones such as red-black trees. The apps pay special attention to interaction. The user can define their own dataset and check in real time how an algorithm or ds behaves. Similar to Visualgo.net and Visualizer from San Francisco State University, but more user friendly for users who are starting from the beginning and can also be useful for those who want to revise their knowledge. Users can navigate through the material both forward and backward. The material is well prepared and pedagogy-oriented.

**Comment by IevgenOvsii** [comment]
@mostafatouny The free version of the app includes access to basic data structures and algorithms such as array, stack, bubble sort, insertion sort, selection sort, as well as the ability to build a binary tree, learn pre-order traversal, and explore DFS algorithm. Users can also create their own graph using the graph constructor and observe how the DFS and BFS algorithms operate. Each topic includes interactive part, theoretical explanations, and sample code in both Java and Python.
In-app purchases unlock additional content, including AVL trees, Red-Black trees, advanced sorting algorithms, MST and Dijkstra’s algorithms.
It is built with Unity3D.

**Comment by mostafatouny** [comment]
At this point, we prefer free-access content with no monetization backdoors. This list is not for advertisement. There are other avenues to expose for-profit applications.

**Comment by IevgenOvsii** [comment]
I understand your decision, but I wanted to clarify that my intention wasn’t to use this as advertising but rather to enhance your list of resources and provide more value to readers. Additionally, I didn’t see any mention in the contribution guidelines that partially free resources aren’t allowed. Thank you for taking the time to review and discuss this.

**Comment by mostafatouny** [comment]
Many people do volunteer content for the community and with no expected return in mind. Look for [Tim Roughgarden](https://www.youtube.com/@timroughgardenlectures1861)'s channel for example. There are other avenues for marketing your application.

**Comment by mostafatouny** [comment]
We are happy to hear back from you, @IevgenOvsii

**Pull request closed without merging**
